@startuml
title communication client server
actor player2 order 30
actor player1 order 10
participant server order 20

server -> server  ++ : preparing threads
server -> server : run all threads
server -> server : affecting ports
server -> server -- : server ready
player1 -> server ++ : Sending information about client
note left
Sending client information
to allow server to communicate back
end note
player2 -> server : Sending information about client
player1 -> server : PLAYER|ID|UP
server -> server : Updating server information
server -> player1 : Player 1 goes up*
server -> player2 : Player 1 goes up*
note left
*
Client recieve the 
updated game environment
end note
@enduml