@startuml
title communication client serveur
actor player2 order 30
actor player1 order 10
participant server order 20

server -> server  ++ : préparation des threads
server -> server : lancement des threads
server -> server : affectation des ports
server -> server -- : serveur pret
player1 -> server ++ : demande de connexion
server -> player1 : connexion accepté
player2 -> server : demande de connexion
server -> player2 : connexion accepté
player1 -> server : déplacement haut
server -> server : mise à jour du serveur
server -> player1 : mise à jour du client
server -> player2 : mise à jour de client
@enduml