@startuml
title interacting with the game environment
actor player1 order 10
participant client order 20
participant server order 30
database scene order 40

player1 -> client ++ : Pressed UP key
client -> server ++ : Player|ID|UP
server -> scene ++ : Updating game envionment
scene -> server -- : game environment updated
server -> client : [game environment]
client -> player1 : player moved up
@enduml